// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutSideNavbar: typeof import('@nutui/nutui-taro')['SideNavbar']
    NutSideNavbarItem: typeof import('@nutui/nutui-taro')['SideNavbarItem']
    NutSubSideNavbar: typeof import('@nutui/nutui-taro')['SubSideNavbar']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
